In [3]:

import pandas as pd

In [9]:

businesses=pd.read_csv("data/businesses.csv")


new_businesses=pd.read_csv("data/new_businesses.csv")

categories=pd.read_csv("data/categories.csv")

countries=pd.read_csv("data/countries.csv")




import os
print(os.getcwd())

c:\wpython\world's_oldest_businesses

In [10]:
businesses.head(10)
new_businesses
categories.head(10)
countries.head(10)

  country_code               country      continent
0          AFG           Afghanistan           Asia
1          AGO                Angola         Africa
2          ALB               Albania         Europe
3          AND               Andorra         Europe
4          ARE  United Arab Emirates           Asia
5          ARG             Argentina  South America
6          ARM               Armenia           Asia
7          ATG   Antigua and Barbuda  North America
8          AUS             Australia        Oceania
9          AUT               Austria         Europe

In [11]:
# What is the oldest business on each continent? Save your answer as a DataFrame
#  called oldest_business_continent with four columns: continent, country, business, and year_founded in any order.
print(businesses.query("country_code == 'FJI'"))
all_businesses = pd.concat([businesses, new_businesses],
                         ignore_index=True)
print(all_businesses.columns)

merged_businesses = pd.merge(
    all_businesses, 
    countries, 
    on='country_code', 
    how='left'
)

oldest_business_continent = merged_businesses.sort_values(by='year_founded', ascending=True).groupby('continent', as_index=False).first()

oldest_business_continent = oldest_business_continent.drop(columns=['category_code','country_code'])

oldest_business_continent

Empty DataFrame
Columns: [business, year_founded, category_code, country_code]
Index: []
Index(['business', 'year_founded', 'category_code', 'country_code'], dtype='str')

       continent                     business  year_founded    country
0         Africa               Mauritius Post          1772  Mauritius
1           Asia                   Kongō Gumi           578      Japan
2         Europe  St. Peter Stifts Kulinarium           803    Austria
3  North America  La Casa de Moneda de México          1534     Mexico
4        Oceania               Australia Post          1809  Australia
5  South America      Casa Nacional de Moneda          1565       Peru

In [12]:
#How many countries per continent lack data on the oldest businesses? Does including new_businesses change this? Count the number of countries per continent missing business data, including new_businesses, and store the results in a 
# DataFrame named count_missing with columns for the continent and the count.

# asia 6 countries missing.
# north amercia 4 countries missing.
# south 3 countries missing.

missing_businesses = countries.merge(
    all_businesses,
    on="country_code",
    how="left"
)

# FIX: Groupby on DataFrame, not Series, and count missing businesses per continent
all_missing_businesses = missing_businesses[missing_businesses['business'].isnull()]
print(all_missing_businesses)
count_missing = all_missing_businesses.groupby('continent').size().reset_index(name='count')
count_missing

    country_code                           country      continent business  \
1            AGO                            Angola         Africa      NaN
7            ATG               Antigua and Barbuda  North America      NaN
18           BHS                           Bahamas  North America      NaN
50           ECU                           Ecuador  South America      NaN
59           FSM   Micronesia, Federated States of        Oceania      NaN
63           GHA                             Ghana         Africa      NaN
65           GMB                            Gambia         Africa      NaN
69           GRD                           Grenada  North America      NaN
79           IRN         Iran, Islamic Republic of           Asia      NaN
89           KGZ                        Kyrgyzstan           Asia      NaN
91           KIR                          Kiribati        Oceania      NaN
92           KNA             Saint Kitts and Nevis  North America      NaN
107          MCO                            Monaco         Europe      NaN
108          MDA              Moldova, Republic of         Europe      NaN
110          MDV                          Maldives           Asia      NaN
112          MHL                  Marshall Islands        Oceania      NaN
131          NRU                             Nauru        Oceania      NaN
138          PLW                             Palau        Oceania      NaN
139          PNG                  Papua New Guinea        Oceania      NaN
143          PRY                          Paraguay  South America      NaN
144          PSE               Palestine, State of           Asia      NaN
153          SLB                   Solomon Islands        Oceania      NaN
160          SUR                          Suriname  South America      NaN
170          TJK                        Tajikistan           Asia      NaN
171          TKM                      Turkmenistan           Asia      NaN
172          TLS                       Timor-Leste           Asia      NaN
173          TON                             Tonga        Oceania      NaN
177          TUV                            Tuvalu        Oceania      NaN
185          VCT  Saint Vincent and the Grenadines  North America      NaN
189          WSM                             Samoa        Oceania      NaN

     year_founded category_code
1             NaN           NaN
7             NaN           NaN
18            NaN           NaN
50            NaN           NaN
59            NaN           NaN
63            NaN           NaN
65            NaN           NaN
69            NaN           NaN
79            NaN           NaN
89            NaN           NaN
91            NaN           NaN
92            NaN           NaN
107           NaN           NaN
108           NaN           NaN
110           NaN           NaN
112           NaN           NaN
131           NaN           NaN
138           NaN           NaN
139           NaN           NaN
143           NaN           NaN
144           NaN           NaN
153           NaN           NaN
160           NaN           NaN
170           NaN           NaN
171           NaN           NaN
172           NaN           NaN
173           NaN           NaN
177           NaN           NaN
185           NaN           NaN
189           NaN           NaN

       continent  count
0         Africa      3
1           Asia      7
2         Europe      2
3  North America      5
4        Oceania     10
5  South America      3

In [15]:
# Which business categories are best suited to last many years, and on what continent are they? 
# Create a DataFrame called oldest_by_continent_category that stores the oldest founding year for each continent and category combination.
#  It should contain three columns: continent, category, and year_founded, in that order.

re_merging = merged_businesses[['year_founded','continent', 'category_code']].merge(
    categories[['category', 'category_code']],
    on='category_code',
    how='left'
)
re_merging
oldest_by_continent_category = re_merging[['year_founded','continent', 'category']]
oldest_by_continent_category
oldest_by_continent_category = oldest_by_continent_category.groupby(['continent','category'],as_index=False).min()
oldest_by_continent_category

        continent                           category  year_founded
0          Africa                        Agriculture          1947
1          Africa               Aviation & Transport          1854
2          Africa                  Banking & Finance          1892
3          Africa  Distillers, Vintners, & Breweries          1933
4          Africa                             Energy          1968
5          Africa                   Food & Beverages          1878
6          Africa         Manufacturing & Production          1820
7          Africa                              Media          1943
8          Africa                             Mining          1962
9          Africa                     Postal Service          1772
10           Asia                        Agriculture          1930
11           Asia               Aviation & Transport          1858
12           Asia                  Banking & Finance          1830
13           Asia          Cafés, Restaurants & Bars          1153
14           Asia                       Conglomerate          1841
15           Asia                       Construction           578
16           Asia                            Defense          1808
17           Asia  Distillers, Vintners, & Breweries          1853
18           Asia                             Energy          1928
19           Asia                   Food & Beverages          1820
20           Asia         Manufacturing & Production          1736
21           Asia                              Media          1931
22           Asia                             Mining          1913
23           Asia                     Postal Service          1800
24           Asia                             Retail          1883
25           Asia                 Telecommunications          1885
26           Asia                   Tourism & Hotels          1584
27         Europe                        Agriculture          1218
28         Europe                  Banking & Finance          1606
29         Europe          Cafés, Restaurants & Bars           803
30         Europe                     Consumer Goods          1649
31         Europe                            Defense          1878
32         Europe  Distillers, Vintners, & Breweries           862
33         Europe         Manufacturing & Production           864
34         Europe                              Media          1999
35         Europe                            Medical          1422
36         Europe                             Mining          1248
37         Europe                     Postal Service          1520
38         Europe                 Telecommunications          1912
39         Europe                   Tourism & Hotels          1230
40  North America                        Agriculture          1638
41  North America               Aviation & Transport          1870
42  North America                  Banking & Finance          1891
43  North America  Distillers, Vintners, & Breweries          1703
44  North America                   Food & Beverages          1920
45  North America         Manufacturing & Production          1534
46  North America                              Media          1909
47  North America                             Retail          1670
48  North America                   Tourism & Hotels          1770
49        Oceania                  Banking & Finance          1861
50        Oceania                              Media          1869
51        Oceania                     Postal Service          1809
52  South America                  Banking & Finance          1565
53  South America          Cafés, Restaurants & Bars          1877
54  South America                            Defense          1811
55  South America                   Food & Beverages          1660
56  South America         Manufacturing & Production          1621